# Generated by Django 3.1.13 on 2021-12-22 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('roomnumber', models.CharField(max_length=255)),
                ('type1', models.CharField(max_length=255)),
                ('type2', models.CharField(max_length=255)),
                ('roompeople', models.IntegerField()),
                ('roommoney', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_author', to=settings.AUTH_USER_MODEL)),
                ('room_likes', models.ManyToManyField(blank=True, related_name='room_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('st_date', models.DateTimeField()),
                ('ed_date', models.DateTimeField()),
                ('usepeople', models.IntegerField()),
                ('leasename', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=255)),
                ('contents', models.TextField(blank=True)),
                ('state', models.CharField(blank=True, choices=[('step1', '신청'), ('step2', '가계약'), ('step3', '예약완료'), ('step4', '취소')], default='step1', max_length=5)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_author', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lease_room', to='leases.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
